### ISSUE TITLE
Unresolved promises may be related to form not updating

### ISSUE THREAD

**Issue by mwiedmann** [formio/react-formio#107]
We are seeing warnings from bluebird about: "a promise was created in a handler but was not returned from it". We dove into the formio code a bit and it looks like the chained then() are missing returns in some cases possibly (createForm may be the main culprit, setSubmission). Then back up in react-formio, returning formio from the createForm then() before initializeFormio adds an additional then() seemed to remove the last warning. We are not familiar with the code obviously though.

The main issue though is that when we initially set the form through the form prop on the Formio component, it shows fine, but then if we assign a new form it doesn't show the updated form. If we assign a another new (3rd) form then the 2nd form shows up. Its like it ends up 1 form behind. We suspect this is related to the unresolved promises but not sure.

**Comment by randallknutson** [comment]
We haven't experienced this recently. The library has been overhauled and now depends on formio.js. If this is still occuring please let us know.
