### ISSUE TITLE
"Attempting to select choice already selected" in console when using Formio component

### ISSUE THREAD

**Issue by sgronblo** [formio/react-formio#109]
The project I'm working on is experiencing this warning. It doesn't seem to cause any actual problem except clogging up the console with warnings that don't contribute any useful information.

Preconditions:

- A select field with a default value

This could potentially be a problem in formio.js.

If I am understanding correctly, rendering this `Formio` component results in a call to `createForm` inside of formio.js's formio.form.js. This code looks like the following:

```
  createForm(form) {
    /**
     * {@link BaseComponent.component}
     */
    if (this.component) {
      this.component.components = form.components;
    }
    else {
      this.component = form;
    }
    return this.onFormBuild = this.render().then(() => {
      this.formReadyResolve();
      this.onFormBuild = null;
      this.setSubmission(this._submission);
    },
      (err) => this.formReadyReject(err)
    ).catch(
      (err) => this.formReadyReject(err)
    );
  }
```

I think `this.render()` indirectly results in a call to setValue on the Select which is fine the first time since no value is selected yet. However in the callback for render there is also a call to `this.setSubmission(this._submission)` which also indirectly results in a call to setValue which is trying to set the selected value to something that was already selected when rendering which results in this warning showing up.

Any suggestions what the cleanest way to fix this could be? Is there anything else I should be checking?

**Comment by randallknutson** [comment]
We did some work recently in formio.js to fix the unhandled promise errors. Can you double check if this is still occurring?
