### ISSUE TITLE
TypeError: _react2.default.createClass is not a function

### ISSUE THREAD

**Issue by aranand2006** [formio/react-formio#110]
./node_modules/react-formio/lib/components/FormComponents/address.js
node_modules/react-formio/lib/components/FormComponents/address.js:25

  22 | 
  23 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
  24 | 
> 25 | module.exports = _react2.default.createClass({
  26 |   displayName: 'Address',
  27 |   mixins: [_valueMixin2.default, _selectMixin2.default, _componentMixin2.default],
  28 |   getTextField: function getTextField() {

**Comment by harrowm** [comment]
The code needs to be changed for React v16 .. the create class has moved to a separate require.

**Comment by johncrisostomo** [comment]
This is sad. I wonder if they will accept a PR immediately? I really need to get this working.

**Comment by johncrisostomo** [comment]
@harrowm That's because the `lib` folder that you get when you `npm install --save formio-react` is already a **built** version (transpiled to ES5 by Babel). So the babel plugin or preset needs to be updated and not necessarily the source code you have on this repo.

**Comment by prycec** [comment]
What is the status of this issue?

**Comment by chamindasion** [comment]
This is due to react version 16 not supporting for createclass. I could overcome by downgrading react and reactdom to version 15. Basically update you package.json file for react and reactdom to version 15. And run npm install again

**Comment by bionicvapourboy** [comment]
Downgrade is not an option because in my app I make use of fragments, portals and so on.

**Comment by randallknutson** [comment]
Use react-formio v2.0 or higher which supports react 16. The react-formio v1.x uses createClass extensively which won't work in react 16.
