### ISSUE TITLE
onElementRender incorrect documentation

### ISSUE THREAD

**Issue by mmiller42** [formio/react-formio#111]
Looks like the `onElementRender` callback takes two parameters: the Form.IO instance and the element. Also, the documentation should state that the `onElementRender` handler must return the element to render (if it does not return anything, the form does not render).

**Comment by mmiller42** [comment]
Also, looks like `npm test` isn't set up in `master` and all the builds are failing.

**Comment by randallknutson** [comment]
This no longer applies to the current version of the renderer.
