### ISSUE TITLE
Edge delete globalObject[safeGlobalName]; issue

### ISSUE THREAD

**Issue by matt3224** [formio/react-formio#112]
Hey, I'm hoping someone is about to help me on an issue i'm seeing in microsoft edge.

I included formio react and setup a form and it works a treat everywhere except edge (even IE11)

This issue is causing the client site to render a white page with no errors in the console. However the below is what the dev environment gives me.

![formio](https://user-images.githubusercontent.com/2401925/34272700-34f629e8-e689-11e7-80e5-809b08308add.png)

I would really appreciate a quick response if at all possible

Thanks!

**Comment by matt3224** [comment]
I've literally done the worst thing possible and warpped that offending code in a condition

```  // Cleanup
  // This can throw errors in some versions of IE for unknown reasons at this time.
    if (window.navigator.userAgent.indexOf("Edge") < 1) {
        if (globalObject[safeGlobalName]) {
            delete globalObject[safeGlobalName];
        }
    }```

**Comment by randallknutson** [comment]
This is no longer applicable to the latest codebase. I'd recommend upgrading to the latest.
