### ISSUE TITLE
Does not support React 16

### ISSUE THREAD

**Issue by bionicvapourboy** [formio/react-formio#113]
Expected result
component Formio for react should run fine on react 16

Actual result
Formio relies on createClass not present in react 16, impossible to embed the forms generated in a new React 16 app.

**Comment by SharadKumar** [comment]
Is there a workaround? @travist

**Comment by travist** [comment]
This would be a question for @randallknutson

**Comment by randallknutson** [comment]
The 2.x branch of react-formio does support react 16. Please use the new version that is based on our javascript renderer.
