### ISSUE TITLE
Multiple forms?

### ISSUE THREAD

**Issue by haraldkrischner** [formio/react-formio#116]
Hello,
I have problems integrating multiple forms on one page. I have different <Form />s, 2 of them fetch the same source. I do not submit the form, because data should not leave the browser but be processed locally inside the browser. The code looks something like this:

```
<Form key={somekey1}
                  src={"https://my.form.io/myform"}
                  submission={this.props.file.submission}
                  onChange={(s) => this.onChange(s,'mainform')} />

<Form key={somekey2}
                  src={"https://my.form.io/addform"}
                  submission={this.props.file.submissionForm1}
                  onChange={(s) => this.onChange(s,'addform1')} />

<Form key={somekey3}
                  src={"https://my.form.io/addform"}
                  submission={this.props.file.submissionForm2}
                  onChange={(s) => this.onChange(s,'addform2')} />
```
Are multiple forms on the same page supported anyway?

Thanks 
Harald

**Comment by AnnTV** [comment]
I have one in parent component and one form in child component. Both fires custom

**Comment by AnnTV** [comment]
I have two forms: one at parent component, another one is at child component.
Parent's onChange method catches events from both forms.
If child <Form /> does not have onChange method, it makes endless loop with onChange event in parent component.
