### ISSUE TITLE
Can not set defaultValue for Radio and Checkbox

### ISSUE THREAD

**Issue by shamanking** [formio/react-formio#120]
When I change or submit Form, it was ok

![s2](https://user-images.githubusercontent.com/5752503/41953654-020d9096-7a01-11e8-8112-a4e4f786a6cd.png)

But how can I re-render value on UI for them, I try to set defaultValue, it was good for another component, but with Radio and Checkbox, it was not ok, although I try in different ways.

Screen Record:

http://recordit.co/xZqkyDXpEO

Anybody can help me, thank you so much!

**Comment by randallknutson** [comment]
Default value only sets on a new submission. If you are rendering an existing submission it will not change the value that is on the form. We did have a bug where checkboxes and radios did not set their defaults properly. It was fixed here: https://github.com/formio/formio.js/pull/527 

This should have fixed your issue. I'm updating the version of formio.js in react-formio to fix the issue.

**Comment by shamanking** [comment]
thanks so much @randallknutson 
It's ok with new version
