### ISSUE TITLE
how to have custom component in react-formio??

### ISSUE THREAD

**Issue by chinmayek** [formio/react-formio#144]

**Comment by randallknutson** [comment]
React-formio uses formio.js as the renderer and form builder. You can use the exact same code to build react-formio components as you can for formio.js. Just create a class that extends BaseComponent and then add the component with Formio.Components.addComponent('checkmatrix', CheckMatrixComponent);

See http://formio.github.io/formio.js/app/examples/customcomponent.html for an example.

**Comment by chinmayek** [comment]
> React-formio uses formio.js as the renderer and form builder. You can use the exact same code to build react-formio components as you can for formio.js. Just create a class that extends BaseComponent and then add the component with Formio.Components.addComponent('checkmatrix', CheckMatrixComponent);
> 
> See http://formio.github.io/formio.js/app/examples/customcomponent.html for an example.

hi.. i got it now, its working, thank you.

**Comment by vishaldenzil** [comment]
Am getting the error 
CheckMatrixComponent.prototype = Object.create(InputComponent.prototype);
TypeError: Cannot read property 'prototype' of undefined
I want to create  custom component like email ...

**Comment by wag110894** [comment]
@vishaldenzil will you please open a new issue for this item?
This issue is almost a year old.
Thanks,
