### ISSUE TITLE
Am not able to catch the form builder schema .After the form creation is done.

### ISSUE THREAD

**Issue by vishaldenzil** [formio/react-formio#146]

**Comment by vishaldenzil** [comment]
Npm version=" 6.2.0"
"react-formio": "^3.0.3",

import React, {Component} from "react";
import {FormBuilder} from 'react-formio';

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
        form:[]
    }
    this.handleData=this.handleData.bind(this);
    this.save=this.save.bind(this);
  }

  handleData(e)
  {
    console.log(e)
    this.setState({form:e});
  }

  save(e)
  {
    console.log(this.state.form)
  }

  render() {
  
      return (
     <div>
        <FormBuilder 
        onSaveComponent={(b) => console.log(b)}
        // onUpdateComponent={(b) => console.log(b)} 
        // onDeleteComponent={(c) => console.log(c)} 
        // onCancelComponent={(d) => console.log(d)} 
        // onChange={(d) => console.log(d)}
        options={{ readOnly: true}}
        form={{display: 'wizard'}} />
     {/* <Values form="wizard" /> */}
     <div>
       <button className="btn btn-primary" onClick={this.save}> submit</button>
     </div>
    </div> 
      )
  }
}
export default FormIoCreation;

**Comment by randallknutson** [comment]
The best way to accomplish this is to listen to the onChange event and save a copy of the form definition into your component's state each time it changes. Then when submit is clicked, you get it out of state instead of from the builder itself.

**Comment by vishaldenzil** [comment]
Here am facing problem is form builders repeatedly displaying the form builders.


import React, { Component } from "react";
import { FormBuilder } from "react-formio";

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
      form: []
    };
    this.handleData = this.handleData.bind(this);
    this.save = this.save.bind(this);
  }

  handleData(e) {
    console.log(e);
    this.setState({ form: e });
  }

  save(e) {
    console.log(this.state.form);
  }

  render() {
    return (
      <div>
        <FormBuilder
          // onSaveComponent={(b) => console.log(b)}
          // onUpdateComponent={(b) => console.log(b)}
          // onDeleteComponent={(c) => console.log(c)}
          // onCancelComponent={(d) => console.log(d)}
          onChange={d => this.handleData(d)}
          options={{ readOnly: true }}
          form={{ display: "wizard" }}
        />
        {/* <Values form="wizard" /> */}
        <div>
          <button className="btn btn-primary" onClick={this.save}>
            {" "}
            submit
          </button>
        </div>
      </div>
    );
  }
}
export default FormIoCreation;

**Comment by randallknutson** [comment]
Are you saying that there are multiple visible versions of the form builder on the page or that it is constantly refreshing?

By setting state it could be triggering a refresh. Thinking this through it might be better to not store it in state as we don't really want to trigger a refresh.
