### ISSUE TITLE
Events triggered on multiple forms on the same page 

### ISSUE THREAD

**Issue by ybo** [formio/react-formio#149]
Hi,

I have two forms in the same react component, and the onChange event in both forms are triggered when I change one of the forms. Here is the code:

```import React, { Component } from 'react'
import { Form } from 'react-formio'

const form1 = {
  components: [
    {
      label: 'Input1',
      type: 'textfield',
      input: true,
      key: 'input1',
    },
  ],
  display: 'form',
  page: 0
}
const form2 = {
  components: [
    {
      label: 'Input2',
      type: 'textfield',
      input: true,
      key: 'input2',
    },
  ],
  display: 'form',
  page: 0
}
class Container extends Component {
  constructor(props) {
    super(props)
  }

  onChange(event, id) {
    console.log('onChange', id)
  }
  render() {
    return (
      <div>
        <Form key='1' form={form1} onChange={(event) => this.onChange(event, '1')} />
        <Form key='2' form={form2} onChange={(event) => this.onChange(event, '2')} />
      </div>
    )
  }
}

export default Container
```

When I change "input1", I am expecting to see only one event is triggered, however, two events are triggered and console prints out:
```
onChange 1
onChange 2
```
Why is the event for form 2 triggered?
I also experience the same issue with the onSubmit event.

**Comment by randallknutson** [comment]
Sounds like this is a bug in the react-formio wrapper or formio.js. 

Here is where event handling is done in react-formio
https://github.com/formio/react-formio/blob/master/src/components/Form.js#L71-L79

Can you check if the issue is that formio.js is firing the events for both forms or if react-formio is listening to both forms in each component? That would help us track down where the issue is.

**Comment by ybo** [comment]
The issue is in the wrapper, as I only see one event got triggered using formio.js directly

**Comment by randallknutson** [comment]
That helps a lot. Is this something you would be able to fix and submit a pull request? If not we can add it to our bug list and prioritize the issue.

**Comment by ybo** [comment]
I tried to play with it today, but I couldn't figure out why, unfortunately. Please add it to your bug list. Thanks

**Comment by randallknutson** [comment]
Will do

**Comment by iobuhov** [comment]
Soon we will publish 3.0.5 that should fix this issue.

**Comment by ybo** [comment]
Thanks! Can you please link the commit or PR to this issue? I would like to know the fix.

**Comment by iobuhov** [comment]
[Fix shared EventEmitter](https://github.com/formio/react-formio/commit/eb3dc6953fcd6e909fa216938feea5c8d615862c)
