### ISSUE TITLE
Auto populate options in select component of form builder from api 

### ISSUE THREAD

**Issue by sireeshav** [formio/react-formio#157]
https://help.form.io/userguide/form-components/#select

I need to auto populate the options dynamically using json coming from API . Pls help. I want to do this inside form builder when adding a select component.

**Comment by travist** [comment]
This is using the URL configuration of the Select component. Here is an example of pulling data from the DOT and into a select dropdown.

http://formio.github.io/formio.js/app/examples/external.html
