### ISSUE TITLE
Form builder is not allowing the change state and browser stop rendering.

### ISSUE THREAD

**Issue by vishaldenzil** [formio/react-formio#161]
When am changing the state of any variable ..form builder is stops responding.
"react-formio": "^2.1.1",
"react": "^16.6.0",
npm =6.2.0,

**Comment by randallknutson** [comment]
I'm not following what is going on here. Can you describe the issue in more detail, perhaps give an example?

This could be an issue where setting the state causes a change event which causes a state change and turns into an infinite loop.

**Comment by vishaldenzil** [comment]
I want to save the schema in onchange

import React, { Component } from "react";
import { FormBuilder } from "react-formio";
import "./index.css";
import $ from "jquery";
import * as axios from "axios";
import { routes } from "./routes";

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
      schema: {},
      display: "form",
      name: ""
    };
    this.handleData = this.handleData.bind(this);
    this.save = this.save.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.formName = this.formName.bind(this);
  }
  handleChange(e) {
    this.setState({ display: e.target.value });
  }
  formName(e) {
    this.setState({ name: e.target.value });
  }
  handleData(e) {
    // $(".nav-tabs").hide()
    // $( "ul.nav.nav-tabs li:nth-last-child(3)" ).hide()
    // $( "ul.nav.nav-tabs li:nth-last-child(2)" ).hide()
    // $( "ul.nav.nav-tabs li:nth-last-child(1)" ).hide()
    this.setState({ schema: JSON.stringify(e) });
  }

  save(e) {
    e.preventDefault();
    let id = this.props.match.params.id;
    let url = "some url";
    axios({
      url: url,
      method: "POST",
      contentType: "application/json",
      dataType: "json",
      data: this.state.schema
    })
      .then(res => {
        this.setState({ form: undefined });
      })
      .catch(res => {
        console.log(res);
      });
  }

  render() {
    const display = this.state.display === "form";
    return (
      <div>
        <div class="form-group">
          <label for="sel1">Select type:</label>
          <div />
          <div>
            <select onChange={this.handleChange} class={{ width: 50 }}>
              <option value="form">form</option>
              <option value="wizard">wizard</option>
            </select>
          </div>
        </div>

        {display ? (
          <FormBuilder
            form={{ display: "form" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        ) : (
          ""
        )}

        {display ? (
          ""
        ) : (
          <FormBuilder
            form={{ display: "wizard" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        )}

        {/* <Values form="wizard" /> */}
        <div>
          <button className="btn btn-primary" onClick={this.save}>
            {" "}
            submit
          </button>
        </div>
      </div>
    );
  }
}
export default FormIoCreation;

**Comment by vishaldenzil** [comment]
import React, { Component } from "react";
import { FormBuilder } from "react-formio";
import "./index.css";
import $ from "jquery";
import * as axios from "axios";
import { routes } from "./routes";

class FormIoCreation extends Component {
  constructor(props) {
    super(props);
    this.state = {
      schema: {},
      display: "form",
       name: ""
    };
    this.handleData = this.handleData.bind(this);
    this.save = this.save.bind(this);
    this.handleChange = this.handleChange.bind(this);
    this.formName = this.formName.bind(this);
  }
  handleChange(e) {
    this.setState({ display: e.target.value });
  }
  formName(e) {
    this.setState({ name: e.target.value });
  }
  handleData(e) {
    // $(".nav-tabs").hide()
    // $( "ul.nav.nav-tabs li:nth-last-child(3)" ).hide()
    // $( "ul.nav.nav-tabs li:nth-last-child(2)" ).hide()
    // $( "ul.nav.nav-tabs li:nth-last-child(1)" ).hide()
    this.setState({ schema: JSON.stringify(e) });
  }

  save(e) {
    e.preventDefault();
    let id = this.props.match.params.id;
    let url = "some url";
    axios({
      url: url,
      method: "POST",
      contentType: "application/json",
      dataType: "json",
      data: this.state.schema
    })
      .then(res => {
        this.setState({ form: undefined });
      })
      .catch(res => {
        console.log(res);
      });
  }

  render() {
    const display = this.state.display === "form";
    return (
      <div>
        <div class="form-group">
          <label for="sel1">Select type:</label>
          <div />
          <div>
            <select onChange={this.handleChange} class={{ width: 50 }}>
              <option value="form">form</option>
              <option value="wizard">wizard</option>
            </select>
          </div>
        </div>

        {display ? (
          <FormBuilder
            form={{ display: "form" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        ) : (
          ""
        )}

        {display ? (
          ""
        ) : (
          <FormBuilder
            form={{ display: "wizard" }}
            onChange={this.handleData}
            options={{ readOnly: true }}
          />
        )}

        {/* <Values form="wizard" /> */}
        <div>
          <button className="btn btn-primary" onClick={this.save}>
            {" "}
            submit
          </button>
        </div>
      </div>
    );
  }
}
export default FormIoCreation;

**Comment by vishaldenzil** [comment]
> I'm not following what is going on here. Can you describe the issue in more detail, perhaps give an example?
> 
> This could be an issue where setting the state causes a change event which causes a state change and turns into an infinite loop.

**Comment by vishaldenzil** [comment]
> I'm not following what is going on here. Can you describe the issue in more detail, perhaps give an example?
> 
> This could be an issue where setting the state causes a change event which causes a state change and turns into an infinite loop.

how to stop this kind of behaviour.

**Comment by randallknutson** [comment]
Is this caused because there an infinite number of change events being fired? We've fixed several issues that were causing infinite change events. If so, try using the latest version of formio.js (may need to manually update it). If you are still getting infinite change events, add the form embed url here and we can investigate which component is causing the issue.

**Comment by kentferolino** [comment]
Also experiencing this. I'm trying to save the schema to the state, onChange props is firing 3 times and throws this error: "Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite."

**Comment by wag110894** [comment]
Hello Kent,

Could you open this issue as a new ticket. 

Thanks,

**Comment by kentferolino** [comment]
Opened new issue: https://github.com/formio/react-formio/issues/228
Thank you @wag110894
