### ISSUE TITLE
formbuilder css?

### ISSUE THREAD

**Issue by aaronliruns** [formio/react-formio#167]
Hello gurus,

Some part of the form builder is rendered on the view in my react app when I followed the sample code . However it looks quite different from the demo I've seen on form.io website. It seems the entire styling is missing and the form builder is not rendered completely. I don't see any error logs from the browser console so I assume the component is brought up correctly but missing styling. 

May I ask if I need to import some CSS library? or the default blue color theme is embeded in the builder component and when i render it I should expect the styling is fine also?

Please take a look at below screenshot and let me know what I need to do?
![screenshot 2019-02-20 at 5 34 38 pm](https://user-images.githubusercontent.com/14796538/53082337-9d4c2f80-3537-11e9-8a0b-52f984d242e5.png)

Node version : v11.10.0
"react": "^16.8.2",
"react-dom": "^16.8.2",
"react-formio": "^3.0.6",
 "react-scripts": "2.1.5"

Thanks a lot

Aaron

**Comment by travist** [comment]
This just means you are missing Bootstrap. You still need to import Bootstrap 4 as a base CSS framework for the Form.io CSS which sits on top of it.
