### ISSUE TITLE
Formbuilder cannot set default value for Address Field Component

### ISSUE THREAD

**Issue by dcoevoet51** [formio/react-formio#168]
Hello, 

I would like to set a default value for the Address Field Component in the builder but it doesn't work.

I have tried the default value field and the Custom Default Value in javascript but nothing works.

Do you have any information or trick to solve that?

Thanks by advance, 

Best regards,

**Comment by travist** [comment]
Thanks for reporting this. We will add this to our development backlog.

**Comment by dcoevoet51** [comment]
Hello, 

Do you have any news or visibility concerning this functionality?

Thanks by advance,

Best regards,

**Comment by jhen1422** [comment]
Hello,

This item is on our development backlog. We do provide services to expedite issue fixes or enhancements. To inquire, please contact support@form.io .

**Comment by wag110894** [comment]
This issue is resolved using the latest version of our 4x Core renderer.
