### ISSUE TITLE
Access to form.emit('componentError', (error) => ...) using React wrapper

### ISSUE THREAD

**Issue by aminmc** [formio/react-formio#178]
Hello,

I would like access to the componentError event that gets emitted if there is an issue with a component within the form. Is there a way to access this using the React wrapper.
I've tried:
```
 ref={(form) => form.on('componentError', (error) => {
   //handle
 } } 
```
but this doesn't work and formio inside form is null.

Any help would be appreciated.

**Comment by randallknutson** [comment]
We could probably add a new event listener in this area: https://github.com/formio/react-formio/blob/master/src/components/Form.js#L83

In the meantime you may be able to do something like
```
form.formio.on('componentError', (error) => {
  // handle
});
```

**Comment by aminmc** [comment]
@randallknutson thanks for you reply.  I'll use the above approach. How do I wait for the promise to resolve? Is there a way to hook into that promise?

**Comment by aminmc** [comment]
Is this acceptable?
```
this.form.createPromise.then((formio) => {
                                 formio.on('componentError', (error) => {
                                   alert(JSON.stringify(error));
                                 })
                               })
```

**Comment by randallknutson** [comment]
Close. Try this:

```
ref={(form) => {
  this.form.createPromise.then(() => {
    form.formio.on('componentError', (error) => {
      alert(JSON.stringify(error));
    })
  })
}}
```

**Comment by aminmc** [comment]
@randallknutson Cool! I owe you a beer...or two!  😄
