### ISSUE TITLE
core-js update seems to have updated with breaking changes

### ISSUE THREAD

**Issue by bradyrichmond** [formio/react-formio#179]
`./node_modules/formiojs/PDF.js
Module not found: Can't resolve 'core-js/modules/es6.array.find'`

The PDF.js file at the formiojs github doesn't have the same references, but I can't get that version to show up locally, and the core-js version that gets installed changed the names of the files that PDF.js is trying to import. I've tried manually changing the file imports but there's also some references to files that don't exist in the current core-js either.

![image](https://user-images.githubusercontent.com/3635253/55203398-6bf2ff00-5188-11e9-9183-8c9d5b764b8c.png)

Or I'm missing something else...

**Comment by travist** [comment]
This seems to have happened with the update of core-js@3. You will need to use 2.x version of core-js. Try typing the following within your application to see if this goes away.

```
npm install --save core-js@2
```

**Comment by bradyrichmond** [comment]
Oh cool, that worked. That could be fixed automatically by updating the package.json file in formio.js, right? Add to dependencies "core-js": "2.x"?

**Comment by travist** [comment]
Yeah I think so. We will add that to our list.

**Comment by bradyrichmond** [comment]
Cool. Thanks!
