### ISSUE TITLE
form builder display not getting updated

### ISSUE THREAD

**Issue by aminmc** [formio/react-formio#186]
I have a state variable that determines whether to use a wizard or normal form. My state gets updated but the form builder still stays the same:
Example:
```js
Formio.Templates.framework = 'semantic';

const formChoices = [{
    key: 'form',
    text: 'Form',
    value: 'form'
}, {
    key: 'wizard',
    text: 'Wizard',
    value: 'wizard'
}];

const CreateFormBuilder = () => {
    const [type, setType] = useState('form');
    return <div>
        <Dropdown
            placeholder='Select type of form'
            openOnFocus
            selection
            options={formChoices}
            onChange={(e, {name, value}) => setType(value)}
        />
        <FormBuilder form={{'display': type}}/>
    </div>
};
```
The setType does trigger the state to be updated so I know that is working, just the builder doesn't update. 

I've even tried:
```js
 {!type ? null : (type === 'form' ? <FormBuilder form={{display: 'form'}}/> : <FormBuilder form={{display: 'wizard'}}/>)}
 ```
The only time this works is when the type is null and you select the type. 

Has anyone else experienced this? I've tried for FormEdit as well and it's the same behaviour.

Formjs version: 4.0.0-beta.28
react-formio: 4.0.0-beta.7

Thanks

**Comment by randallknutson** [comment]
We've seen this in the formio.js library which is underlying react-formio so it is a known issue. It's on our list to track down why it doesn't switch yet but we haven't had a chance to work on it yet.

**Comment by aminmc** [comment]
Hi @randallknutson 

Just wanted to let you guys know that I've upgraded formio and this is no longer an issue.

Thanks guys!
