### ISSUE TITLE
Select Component rendering is broken

### ISSUE THREAD

**Issue by dheerajsh** [formio/react-formio#190]
Hi Support Team,

This is like first I tried  the `select component` and below error is on browser console when click on the component.

`choices.js?d6ea:2541 Uncaught TypeError: Cannot create property 'keyCode' on boolean 'false'
    at Choices._handleChoiceAction (choices.js?d6ea:2541)
    at Choices._onMouseDown (choices.js?d6ea:3121)`

This Error is on the console while the UI is totally broken for the select component. I am using the react-formio lib.

![image](https://user-images.githubusercontent.com/29531396/57683787-a04e4c00-765e-11e9-9c66-323a78b578b0.png)

Please help here?

**Comment by wag110894** [comment]
It is probably related to the choices upgrade and could be that you need to update your CSS from the choices.js library. Can you verify the CSS is the latest from them?

**Comment by dheerajsh** [comment]
@wag110894 choices.js is already at the latest version in formiojs bundle. plus for rendering, I am not sure for rendering choices.js is responsible. it throws an error after clicking on drop down.

**Comment by travist** [comment]
You need to include the ```formio.min.css``` file in your application. This includes the choices.js css.

**Comment by dheerajsh** [comment]
Fixed by including `choices.min.css`
