### ISSUE TITLE
delete Submission is not working

### ISSUE THREAD

**Issue by dheerajsh** [formio/react-formio#195]
HI Support Team,
Thanks for all the help you guys are providing, really appreciate.

Now I got stuck in another issue.
I need to provide the functionality to updated and delete existing submission to users in the forms.
In a form, I added a button whose actions is `Delete` but when I click on this it gives error on console 

`Uncaught TypeError: Cannot read property 'deleteSubmission' of null
    at Webform.deleteSubmission (Webform.js?9794:1218)
    at EventEmitter.eval (Webform.js?9794:935)
    at EventEmitter.emit (eventemitter2.js?d4eb:351)
    at ButtonComponent.emit (Component.js?6313:173)
    at HTMLButtonElement.eval (Button.js?383c:333)
deleteSubmission @ Webform.js?9794:1218
(anonymous) @ Webform.js?9794:935
EventEmitter.emit @ eventemitter2.js?d4eb:351
emit @ Component.js?6313:173
(anonymous) @ Button.js?383c:333`

**Comment by randallknutson** [comment]
How are you embedding this? In order to do the delete, you need to supply either the src or url attribute to the form component. That way it knows the url for sending the delete request. 

If you are sending the form prop, use url as well which is the url of the form. Otherwise you can just use the src prop.

**Comment by dheerajsh** [comment]
It works 😊. But sometime it still give the error and i had to provide the url of submission not form to make it work. But I wanted to close the form as well when user delete it.
Does it provide a callback? I saw on docs there are actions as well for these events but i am not sure how to use them with form component. Is there any example of using actions and selectors with form component?

**Comment by randallknutson** [comment]
Here are the available prop functions that you can add to a form: https://github.com/formio/react-formio/blob/master/src/components/Form.js#L22-L34

I don't see one for delete right now but that is something we could add. We may just need to add an "onAny" handler to pass all events.

**Comment by dheerajsh** [comment]
Maybe I could add it and create a pr.🙂.
I have also noticed there is no way to add hooks like formiojs, so if i wanted to update the submission or validate it before submit, I can't do it as of now. And if i add on submit props does provide the submission but it's a copy of submission, any changes i made in submission here didn't reflacted

**Comment by randallknutson** [comment]
You can pass hooks like formiojs using the options prop.

You can use refs to set the submission manually. For example:
```
<Form ref={form => {
  form.submission.data.foo = 'bar';
}} />
