### ISSUE TITLE
File Upload Problem

### ISSUE THREAD

**Issue by marou8520** [formio/react-formio#2]
Hello,

Im using the localhost react-formio mode and i want to use the file upload on my form to upload pictures to localhost wisdom db.
So when i use the the interface of formio to add a picture,it works without problem,but when i try to use it on my react project the form does not appear and i got this error on my browser console:
![capture d ecran 2016-01-26 a 13 11 23](https://cloud.githubusercontent.com/assets/16682925/12580275/66907654-c42e-11e5-9467-91adaff46e05.png)

Sorry for my bad english.

**Comment by randallknutson** [comment]
File upload is not yet supported in React. We will be adding that soon. I've updated the renderer to notify users when unsupported components are used on a form instead of crashing the renderer.

We are working to get all components supported here shortly.
