### ISSUE TITLE
React and webpack warnings

### ISSUE THREAD

**Issue by batusai513** [formio/react-formio#20]
hi, i'm working with this library in a webpack application, but i'm getting these warnings:
```bash
Warning: React.__spread is deprecated and should not be used. Use Object.assign directly or another helper function with similar semantics. You may be seeing this warning due to your compiler. See https://fb.me/react-spread-deprecation for more details.
```

also i'm getting this in webpack:
```bash
WARNING in ./~/react-formio/dist/Formio.js
Critical dependencies: This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
@ ./~/react-formio/dist/Formio.js 343:501-508
```

Al so, when using a date component in form.io, the react component associated with the date component does not have any styles.

**Comment by randallknutson** [comment]
Both of these are harmless warnings. You can eliminate them by using this to include Formio

`
var Formio = require('react-formio/src/Formio.jsx');
`

**Comment by batusai513** [comment]
@randallknutson that wont work because i'm using webpack and i'm excluding node_modules, so it throws when it find jsx, i'm going to try to change the main from package.json and add a script to build but not minify the bundle.

**Comment by randallknutson** [comment]
I'm in favor of this change so let me know if you figure it out.

**Comment by batusai513** [comment]
@randallknutson #26

**Comment by randallknutson** [comment]
Merged. Thank you!
