### ISSUE TITLE
[BUG] Panel component is not saving changes

### ISSUE THREAD

**Issue by giovanidalpiva** [formio/react-formio#213]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.0.0-beta.53
- Frontend framework: 4.0.0-beta.33
- Browser: Google Chrome
- Browser version: 74.0.3729.169 (Official Build) (64-bit)

## Steps to Reproduce
1. create a new form with wizard
2. edit one panel component and apply a simple conditional rule
3. save the changes

## Expected behavior
was expected that the changes applied were saved and applied 

## Observed behavior
the system is not keeping the changes 

## Example
![Screen Shot 2019-06-28 at 5 46 40 PM](https://user-images.githubusercontent.com/2424751/60370825-ef153280-99cd-11e9-973b-a31a590a1905.png)
![Screen Shot 2019-06-28 at 5 47 08 PM](https://user-images.githubusercontent.com/2424751/60370826-efadc900-99cd-11e9-8aac-6f72a2fc3c6f.png)
![Screen Shot 2019-06-28 at 5 47 33 PM](https://user-images.githubusercontent.com/2424751/60370828-efadc900-99cd-11e9-8e49-ae482ebd0531.png)

**Comment by randallknutson** [comment]
Thanks for the report. We have this issue in our backlog already where wizard pages are not correctly saving the conditional settings. We will be fixing it here very shortly as it is a high priority.

**Comment by randallknutson** [comment]
Should be fixed with https://github.com/formio/formio.js/commit/e22125555a9ac4416b53471008d2e14a0b2b5b56

**Comment by giovanidalpiva** [comment]
fixed, new bugs start to happen and I will open other issues
