### ISSUE TITLE
[BUG] When edit a wizard is not possible to see the panels after the first, and the add button does not work

### ISSUE THREAD

**Issue by giovanidalpiva** [formio/react-formio#215]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.0.0-rc.1
- Frontend framework:4.0.0-rc.1
- Browser: Google Chrome
- Browser version:74.0.3729.169 (Official Build) (64-bit)

## Steps to Reproduce
scenario 1:
1. create a new wizard resource
2. try to add a new step/ panel

scenario 2:
1. edit a resource that was configured in a preview form.io version, and that had more than one panel in the wizard 

## Expected behavior
scenario 1:
was expected that when you click the add button, a new panel for the wizard was created

scenario 2:
was expected to see all the panels/ steps of the wizard, and so to be able to navigate between then to add or remove components

## Observed behavior
scenario 1:
the button to add a new panel in a wizard is not working, no action happens when click the add button

scenario 2:
you can see just the first panel, all the others are not showed in the wizard configuration. If the configuration "Display as" is changed to form, the panels are showed 

## Extra
In the previous version this behavior was working fine

## Example
![Screen Shot 2019-07-03 at 10 07 57 PM](https://user-images.githubusercontent.com/2424751/60633316-76084780-9de0-11e9-88eb-9bcd52bfecf8.png)
![Screen Shot 2019-07-03 at 10 08 19 PM](https://user-images.githubusercontent.com/2424751/60633317-76084780-9de0-11e9-94a6-acd1cdef28c5.png)

**Comment by randallknutson** [comment]
We had a bug in 4.0.0-rc.1 that caused wizard pages to not display. This should be fixed in the latest rc. Can you upgrade and retest?
