### ISSUE TITLE
getForm(name) action not working. Am I doing something wrong?

### ISSUE THREAD

**Issue by DeBueno** [formio/react-formio#217]
Dispatching the getForm(name) action doesn't seem to work.

```javascript
mapDispatchToProps = (dispatch) => {
  return {
    getForm: (name) {
      dispatch(getForm(name));
    }
  }
}
```

```javascript
componentWillMount = () => {
  /** I don't have an ID beforehand, just the form name */
  this.props.getForm("form-name", undefined, (err, form) => {/** do something*/})
}
```

It throws an error on `react-formio/lib/modules/form/selectors.js:11`

When I change the line `react-formio/lib/modules/form/actions.js:87` from
```javascript
var form = (0, _selectors.selectForm)(name, getState());
```
to
```javascript
var form = (0, _selectors.selectForm)("form", getState());
```

It works fine. What am I missing? I don't feel I should mess with the code.

**Comment by randallknutson** [comment]
The name should match the name set when instantiating the reducer in the redux store. That way the reducer knows which actions to listen to. If you change it to "form" it will populate this reducer: https://github.com/formio/react-app-starterkit/blob/master/src/rootReducer.js#L6

**Comment by DeBueno** [comment]
Oh, thanks! It works!
