### ISSUE TITLE
Can't get the Formio instance from a ref

### ISSUE THREAD

**Issue by DeBueno** [formio/react-formio#226]
I have a wizard form and I need it's reference.
 ```javascript
<Form src={AppConfig.apiUrl +"/"+ formName} ref={form => this.wizard = form}/>
```
However, `this.wizard.formio` is undefined.

**Comment by randallknutson** [comment]
You may need to wait for this.wizard.ready to finish. It is a promise so if you wait then formio should be available.

**Comment by DeBueno** [comment]
`this.wizard.ready` is also undefined.
The strangest part is that the formio field is set. Here a quick log.
```javascript
    console.log("Wizard");
    console.log(this.wizard);
    console.log("ready");
    console.log(this.wizard ? this.wizard.ready : null)
    console.log("formio")
    console.log(this.wizard ?  this.wizard.formio : null);
```

![output](https://user-images.githubusercontent.com/14241748/61373014-0463db00-a86f-11e9-9fea-a6725b0d8cc3.png)

**Comment by DeBueno** [comment]
Managed to get it. The problem was that I was trying to get it on render() function. I triggered the update with onChange prop of the form and set the state of the form within my own component.

```javascript
...
setRef = (ref) => {
...
    this.setState({form: ref.current});
 }
...
render(){
...
<Form src={AppConfig.apiUrl + formName} ref={this.wizard} onChange={() => this.setRef(this.wizard)}/>
...
}
...
```
