### ISSUE TITLE
[BUG] FormBuilder onChange props, using schema for setState is throwing error.

### ISSUE THREAD

**Issue by kentferolino** [formio/react-formio#228]
## Environment
- Formio.js version: 4.0.0-rc.12
- React-formio version: 4.0.0-rc.7
- Frontend framework: React
- Browser: Chrome
- Browser version: Chrome 75

## Steps to Reproduce
1. Embed FormBuilder in react app (create-react-app)
2. Provide onChange prop, use the schema to change state
```
import React, { useState } from 'react';
import { FormBuilder } from 'react-formio';

const App = () => {
  const [schemaState, setSchemaState] = useState();
  return (
    <div>
      <FormBuilder
        form={{ display: 'form' }}
        onChange={(schema) => setSchemaState(JSON.stringify(schema))}
      />
    </div>
  );
}

export default App;
```

## Expected behavior
Should update state without error.

## Observed behavior
Not updating state. 
Throws an error: 'dragula.js:710 Uncaught TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.'

**Comment by aminmc** [comment]
Related to #208 and PR outstanding https://github.com/formio/react-formio/pull/222. 

Guys, this issue has been ongoing for a while now. Can we get an update on when this will be resolved or can we just revert the original changes to get this to work?

**Comment by aminmc** [comment]
@randallknutson @YuryRybak Can we please get an update on this?

**Comment by randallknutson** [comment]
Yury has been working on getting this resolved correctly. It has something to do with various types of state management (redux or other) and works with the way we currently use it. He has some ideas on how to make it more tolerant of various ways of passing in the props but hasn't had a chance to finish it yet.

**Comment by lukeburns** [comment]
If you don't need FormBuilder to update with state changes, then you can isolate it from its parent like the following.

```js
import React, { useState } from 'react';
import { FormBuilder } from 'react-formio';

const App = () => {
  const [schemaState, setSchemaState] = useState();
  return (
    <Isolate>
      <FormBuilder
        form={{ display: 'form' }}
        onChange={(schema) => setSchemaState(JSON.stringify(schema))}
      />
    </Isolate>
  );
}

export default App;

class Isolate extends React.Component {
  shouldComponentUpdate () {
    return false // prevent parent state changes from re-rendering FormBuilder
  }
  render () {
    return <React.Fragment>
      {this.props.children}
    </React.Fragment>
  }
}
```

**Comment by aminmc** [comment]
@lukeburns Thanks for the workaround however as you mentioned it won't work in our case. @randallknutson any progress on resolving this?

**Comment by lukeburns** [comment]
@aminmc what is your use case? are you programmatically managing the schema?

**Comment by aminmc** [comment]
'FormBuilder does need to update with state' -> we do that @lukeburns, uses can change between form and wizard.

**Comment by kentferolino** [comment]
It seems like the re-rendering of FormBuilder is producing the error (when state is changed).
I tried your solution @lukeburns , it is working for my use case. Are there any downside with this work around? I'm just wondering. Thanks for helping @aminmc  and @lukeburns

**Comment by aminmc** [comment]
@jhen1422 This is still an open issue for us due the fact that we need to pass state into the form builder. Otherwise when a user switches between form and wizard we lose the components that was added. This was a feature of the old form builder
