### ISSUE TITLE
Is there any way to rename the "Submit Form" Button (Main Submission Button)?

### ISSUE THREAD

**Issue by kentferolino** [formio/react-formio#231]
Hi,

Is there a way to change the text of the main submission button? From "Submit Form" to something like "Save".

Thank you!

**Comment by randallknutson** [comment]
Buttons on forms are components on the form so you should be able to modify them in the builder. It sounds like you are talking about the Wizard form buttons though which are slightly different. If you are using the 4.x branch of our renderer you can override the template at https://github.com/formio/formio.js/blob/4.x/src/templates/bootstrap/wizard/form.hbs to change the button title.

**Comment by kentferolino** [comment]
Thanks @randallknutson . Was able to override the name of the buttons.
