### ISSUE TITLE
[BUG] react-formio fails on `prepublish` during `npm install`

### ISSUE THREAD

**Issue by akaustav** [formio/react-formio#232]
## Environment

- **react-formio branch/tag:**
  - [x] master
  - [x] 1x
- **NodeJS version:** v12.7.0
- **npm version:** 6.10.0
- **Operating System:** Microsoft Windows 10 version 1903 (May 2019 Update)

## Steps to Reproduce

1. Clone `react-formio`
1. Run `npm install`

## Expected behavior
`npm install` should complete successfully.

## Observed behavior

`npm install` fails with the following warning and error messages on the console.

```console
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sangh\AppData\Roaming\npm-cache\_logs\2019-07-31T03_23_01_083Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-formio@4.0.0-rc.11 prepublish: `npm run lint; npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-formio@4.0.0-rc.11 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sangh\AppData\Roaming\npm-cache\_logs\2019-07-31T03_23_01_165Z-debug.log
```

**Comment by akaustav** [comment]
## More information

From `package.json`, it looks like the `prepublish` script executes two other scripts sequentially:

- `lint`
- `build`

Extract from package.json:

```json
{
  "scripts": {
    "build": "babel ./src --ignore=*.spec.js --out-dir ./lib --presets es2015,react,stage-2",
    "lint": "eslint src",
    "prepublish": "npm run lint; npm run build"
  }
}
```

Found that semi-colons (`;`) does NOT work to delimit two sequential scripts in the Windows 10 command prompt. Hence, npm in Windows 10 searches for the target `lint;` instead of `lint`.

It appears that we can use `&&` (double ampersand) to delimit sequential npm scripts. This seems to be working in both Windows and Unix based systems.

**Comment by randallknutson** [comment]
Thanks. We can make this change next time we do a build. Is this something you could quickly do a pull request for so we don't lose it?

**Comment by akaustav** [comment]
Already done. See PR #233. Although, I pull only into the 1.x branch.

**Comment by akaustav** [comment]
@randallknutson Thanks for merging my PR #233. I do not have access to a macbook. So I am not sure if this indeed works on a mac. Please verify on your macbook when you can.

Also, the change was done only in the `1.x` branch.
After your confirmation, you should be able to do the same change in the master too.

Let me know if you'd rather I open a PR for making the same fix in master too.

**Comment by randallknutson** [comment]
Yep. I'll get that in the other branches as well.
