### ISSUE TITLE
[BUG] Hiding buttons with conditionals. Uncaught TypeError: Cannot read property 'loading' of null

### ISSUE THREAD

**Issue by kentferolino** [formio/react-formio#238]
## Environment
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: ^3.25.3
- React-formio version: ^4.0.0-rc.10
- Frontend framework: React ^16.8.6
- Browser: Chrome

## Steps to Reproduce
1. Create a form
2. Add fields including a radio button
3. Add a button, and set the conditional that when a certain value of a radio button, the button will show

## Expected behavior
-Shouldn't have any errors or delay in changing values.

## Observed behavior
- When changing other field values, there are delays. Console log displays 
```
Uncaught TypeError: Cannot read property 'loading' of null
    at ButtonComponent.setLoading (Component.js:2199)
```
## Example
![image](https://user-images.githubusercontent.com/14606704/63209759-e8768200-c117-11e9-9197-8cc47efb440d.png)

**Comment by jhen1422** [comment]
@kentferolino 
This should be resolved in the latest 4x renderer. Please let us know otherwise.
