### ISSUE TITLE
[BUG] Lack of remove button for multiple File Uploads when saving as Base64

### ISSUE THREAD

**Issue by sukrit-adhikari** [formio/react-formio#239]
![image](https://user-images.githubusercontent.com/11311029/63358788-9e6ce680-c339-11e9-9e42-9aac0033da36.png)

As you can see in the screenshot, there is no remove button/icon to remove one of the two files.

**Comment by randallknutson** [comment]
Can you check if you have included the icon library? I can't remember if it is glyphicons or font awesome. The remove is probably there but you can't see it because the icon library is missing.

**Comment by sukrit-adhikari** [comment]
Fixed this with this SCSS

.glyphicon.glyphicon-remove {
  &:hover {
    cursor: pointer;
  }
  &::after {
    content: "x";
  }
}

Thanks
