### ISSUE TITLE
[Question] Bundled for the client using

### ISSUE THREAD

**Issue by hoanghiep** [formio/react-formio#240]
Hi, Can i bundle this project and use it in client side? I tried browserify but it didn't work.

**Comment by randallknutson** [comment]
You can definitely use it in the browser. That's what it is designed for. We typically use it with a module bundler like webpack.

**Comment by hoanghiep** [comment]
Hi @randallknutson. I plan to use it with spring boot. Could you give me a sample webpack configuration to bundle it? Thank you.
