### ISSUE TITLE
[BUG] getSubmissions with query arg has no effect

### ISSUE THREAD

**Issue by darabi** [formio/react-formio#242]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 1.50.0 Docker image built locally
- formio/react-app-starterkit@8511dd2743
  - Formio.js version: 4.0.0-rc.21
  - Frontend framework: = react-formio 4.0.0-rc.18 e5718c5af8   
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1. create a form and some submissions, e.g. `Person` with components `name` (`Text Field`) and `age` (`Number`)
2. modify react-app-starterkit and create a component like `react-app-starterkit/src/views/Form/Item/Submission/List.js` which uses a `SubmissionGrid` with such a `mapDispatchToProps`:

```
const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    getSubmissions: (page, query) =>  dispatch(getSubmissions('submissions', page, { "data.age__gt": 40 } , ownProps.match.params.formId))},
```

3. add a route for it in `src/App.js`

## Expected behavior

When the component mounts, `getSubmissions` should retrieve only those `Person` instances with `age > 40`.
 
## Observed behavior

All `Person` instances are loaded.

## Example

cf. above

**Comment by darabi** [comment]
I hope this is the correct interpretation of this part of the README (emphasis mine):

### submissions
...

#### Actions
| Name | Parameters | Description |
|---|---|---|
| ```getSubmissions``` | name: string, page: integer, params: object, formId: string | Fetch a list of submissions from the server. **```params``` is a query object to filter the submissions.** |

**Comment by randallknutson** [comment]
Thanks for finding this. We intended this all along but somehow missed combining the query. I'll get it merged in the next build.

**Comment by darabi** [comment]
Thanks for your quick reply. I have just opened #244 which is very similar. Will push a PR for that one shortly.
