### ISSUE TITLE
[BUG] onRender and onLoad don't get triggered for first time rendering

### ISSUE THREAD

**Issue by gith-amitm7** [formio/react-formio#248]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 4.0.0
- Formio.js version: 4.0.8
- Frontend framework: React
- Browser: Chrome
- Browser version: 76.0.3809.100 (Official Build) (64-bit)

## Expected behavior
onRender handler should be called

## Observed behavior
No calls made to handlers

## Example
1. Took src > views > Auth > Login.js file from the example at https://github.com/formio/react-app-starterkit
2. Modified Login.js
/*****************************************************************************************/
```
import React, { Component } from "react";
import { connect } from "react-redux";
import { Form } from "react-formio";
import { push } from "connected-react-router";
import { AppConfig, AuthConfig } from "../../config";
import { setUser } from "react-formio";

const Login = class extends Component {
  changeHandler = submission => {
    console.log("ch-form instance:", submission, this);
  };
  renderHandler = () => {
    console.log("rh-form instance:", this);
  };
onFormLoad = () => {
    console.log("ofl-form instance:", this);
  };
  submitHandler = submission => {
    console.log("sh-form instance:", this, submission);
  };
  render() {
    return (
      <Form
        src={this.props.src}
        onRender={this.renderHandler}
        onFormLoad={this.onFormLoad}
        onChange={this.changeHandler}
        onSubmit={this.submitHandler}
      />
    );
  }
};

const mapStateToProps = () => {
  return {
    src: AppConfig.projectUrl + "/" + AuthConfig.login.form
  };
};

const mapDispatchToProps = dispatch => {
  return {
    onSubmitDone: submission => {
      dispatch(push(AuthConfig.authState));
      dispatch(setUser(submission));
    }
  };
};

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Login);

```
/*****************************************************************************************/

I am unable to get any consoles with "rh-form instance" and "ofl-form instance" texts

**Comment by jhen1422** [comment]
@gith-amitm7 
Thank you for the report. We have created a ticket for the issue and will review during our planning meeting. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by randallknutson** [comment]
This should be fixed with this pull request https://github.com/formio/formio.js/pull/1700
