### ISSUE TITLE
[BUG]  Cannot read property 'destroy' of null

### ISSUE THREAD

**Issue by Uysim** [formio/react-formio#255]
I use react formio version 4.2.0
my code 
```reactjs
 <FormBuilder
    form = {form_json}
    onChange={(schema) => this.onChange(schema)}
 />
```
Error I got 

<img width="1275" alt="Screen Shot 2019-10-07 at 3 15 36 PM" src="https://user-images.githubusercontent.com/10666612/66295523-c0d0b880-e915-11e9-8547-e922443f5603.png">

**Comment by aiwebb** [comment]
Thanks @Uysim - this appears to be in issue in core formio.js, so we're going to track it in formio/formio.js#1817.
