### ISSUE TITLE
how to set nosubmit flag

### ISSUE THREAD

**Issue by jpshilton** [formio/react-formio#256]
Hi there,
I'm trying to set the `nosubmit` flag to `true` and submit to a custom endpoint as described here: https://formio.github.io/formio.js/app/examples/customendpoint.html

What would be the best way to accomplish this using the `react-formio`  `Form` component?

**Comment by jpshilton** [comment]
That didn't work. It seems the `nosubmit` property has to be set on the `form` itself and can't be passed as part of  `options`.

**Comment by randallknutson** [comment]
The way to do that then would be something like this:

<Form
  src="..."
  ref={(form) => form.nosubmit=true}
/>

it may be form.instance.nosubmit so try both ways.
