### ISSUE TITLE
[BUG] Client request error: unable to verify the first certificate

### ISSUE THREAD

**Issue by sukrit-adhikari** [formio/react-formio#258]
![image](https://user-images.githubusercontent.com/11311029/66781329-f723b000-eea0-11e9-8cdc-f819d009f9e4.png)

This might not be a bug. Was trying to integrate SSO - OpenID (Resource Authentication) and getting this error. "Client request error: unable to verify the first certificate"

Any idea what might be causing it?

**Comment by randallknutson** [comment]
There is a communications issue between our server and the openid server regarding the ssl certificate. Can you check if your integration settings for openid are correct?

**Comment by sukrit-adhikari** [comment]
Closing because of what we are using is on premise setup and we need to figure this with our security team. thanks
