### ISSUE TITLE
[BUG] FormBuilder - Default value for "template" being overridden on load

### ISSUE THREAD

**Issue by MaximeTroiano** [formio/react-formio#262]
## Environment
Please provide as many details as you can:

- Hosting type
  - [?] Form.io
  - [X] Local deployment
    - Version: 4.2.1
- Formio.js version: 
- Frontend framework: React
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create a builder with components having default values
2. Set the default value of the attribute "Template" of a "List"
3. On load of the FormBuilder with the Form JSON, the template field is being overridden by a merge of "<span>{{ [item].[value] }}</span>"

## Expected behavior
It should take the default value first, if none, calculate as it does today

## Observed behavior
It calculates even if there is a default value

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

Part of the default attributes of the FormBuilder-components:

```js
{
        ...
        valueProperty: "id",
        dataType: "string",
        template: "<span>{{ AnyValueYouWant }}</span>",
        selectValues: "",
        searchEnabled: true,
        selectThreshold: 0.3,
        readOnlyValue: false,
        ...
}
```

When rendered, the value is being overridden:
![image](https://user-images.githubusercontent.com/13046607/67838504-b9a26200-faf1-11e9-81f3-cda8e0ee33a2.png)

**Comment by jhen1422** [comment]
@MaximeTroiano This should be resolved in the latest version of 4x.

**Comment by MaximeTroiano** [comment]
`
{}
`

> @MaximeTroiano This should be resolved in the latest version of 4x.

What do you mean? I'm on version 4.2.1 of Form.io.

**Comment by jhen1422** [comment]
@MaximeTroiano 
The latest version of formio.io js is 4.6.2. Please upgrade the version to resolve the issue.
