### ISSUE TITLE
Loading content on select field

### ISSUE THREAD

**Issue by slaterx** [formio/react-formio#271]
I am attempting to load a set of values in a select component. The values would come from an JWT authenticated and customized API call, so instead of defining an URL for the field, I'm fetching the API myself and trying to pass the results to the form. 

So, for the following React component:

```bash
<Form src={thisSrcAddress}
                  submission={{ data: this.state.content }}
                  options={{...{template: 'bootstrap3', iconset: 'fa'},  ...options}}
                  onSubmit={(content) => this.onSubmitHandler(content)} />
```

With the following form:

```bash
{
    "input": true,
    "tableView": true,
    "label": "Staff Member",
    "key": "Staff",
    "placeholder": "",
    "data": {
        "values": [
            {
                "value": ""
            }
        ],
        "json": "",
        "url": "",
        "resource": "",
        "custom": ""
    },
    "dataSrc": "values",
    "valueProperty": "",
    "defaultValue": "",
    "refreshOn": "",
    "filter": "",
    "authenticate": false,
    "template": "<span>{{ item.value }}</span>",
    "multiple": false,
    "protected": false,
    "unique": false,
    "persistent": true,
    "hidden": false,
    "clearOnHide": true,
    "type": "select"
},
```

How can I load the following json as a set of values?

```bash
{
values: [
  {value: "Jack"},
  {value: "John"},
  {value: "Maria"},
  {value: "Paul"}
]
}
```

**Comment by aminmc** [comment]
I haven’t tested this myself but what you could try is setting the data source for the select box to be custom and there is an option to set the values for custom in which case you could do values=data.myselectData. 

You’ll need to set mySelectData in the submission

The other option is to create a fetch plugin where you can get the jwt token and formio will use that when making a request to get the data.

**Comment by aminmc** [comment]
@slaterx here is a jfiddle showing the above:
https://jsfiddle.net/xv6rqp4h/

It's using raw formiojs but you should be able to apply the principal to the react-formio.  as mentioned before if you want you could create a custom fetch which can get the jwt token and that can be passed to Formio.  Here is a [link](https://github.com/formio/formio.js/wiki/Fetch-Plugin-API)

**Comment by slaterx** [comment]
@aminmc thank you for your assistance! Updating also the following fields:

```bash
(...)
"dataSrc": "custom",
"dataType": "string",
"valueProperty": "value",
```

in my form, was necessary to make it work. Specifically for react-formio, I had to wrap the API call result into the submission object I was already using to load on my form. I followed this answer [here](https://stackoverflow.com/a/49754488) to create a Promise.all to handle all API calls and this [other one](https://stackoverflow.com/a/43041334) to nest `mySelectData` inside the main object, `content`. Here's the final result, documented for posterity (including Future me):

```bash
        Promise.all([
            fetch(apiCallOne),
            fetch(apiCallTwo)
        ])
            .then(([res1, res2]) => Promise.all([res1.json(), res2.json()]))
            .then(([data1, data2]) => {
                this.setState({
                    content: data1
                });
                let content = {...this.state.content};
                content.mySelectData = data2;
                this.setState({content});
            });
```
