### ISSUE TITLE
Upgrading formiojs in react-formio

### ISSUE THREAD

**Issue by prem911** [formio/react-formio#276]
The latest 3.x version of react-formio is 3.1.12 and it has "formiojs": "^3.16.1" as dependency.
There have been few defect fixes in formiojs and the latest version available is 3.29.4

What is the process to request a new react-formio version pointing to the latest formiojs version?
Should we fork and build it ourselves? Should we raise a PR for it?
Are there any react component level changes that also need to be studied from the defect fixes that needs to be applied?

**Comment by randallknutson** [comment]
Upgrading the 3.x version shouldn't cause any regressions. Since 3.16.x to 3.29.x is a minor update npm should automatically do this for you when you install. However, if you want to raise a PR it would probably be easiest so we do it next time we do some builds.

**Comment by ezedox** [comment]
Thanks @randallknutson for the quick response.
Right now I have backported a fix in formiojs on Select to 3.x. In the defect it was mentioned that this will not make it to 3.x as it is a breaking change and will be available for 4.x

So, I m planning to fork both formiojs and react-formio.

In the forked version of formiojs, I have changed the package name to @user/formiojs
Im not able to publish this package.
npm publish lib --tag 3x  is throwing 
403 Forbidden - PUT https://registry.npmjs.org/formiojs - You do not have permission to publish "formiojs". Are you logged in as the correct user?

Are there other configurations to be changed to publish this as a different package?
Once it is published, I plan to add it as a dependency in react-formio.

Any pointers?

**Comment by randallknutson** [comment]
I don't think you will be able to publish the package to the npm registry due to permissions. What you'll need to do if you fork it is replace the formiojs version in react-formio with a github link to your fork. This will allow npm to install correctly using your forked versions.

If at all possible I'd recommend upgrading to 4.x. At this point it is significantly improved from the 3.x branch. I understand if that isn't possible but would be a good idea if there is any way of doing it.

**Comment by ezedox** [comment]
I was able to fork both the projects and get them to work. package.json was needed to be changed in 2 places in formiojs :)

**Comment by randallknutson** [comment]
Glad you got it to work! Hopefully at some point you can start using our main libraries again.
