### ISSUE TITLE
Instructions for using formio.js in react-formio for bug fix ?

### ISSUE THREAD

**Issue by silent-vim** [formio/react-formio#282]
Hi, I am trying to test some bug fixes in formio.js and using it in react-formio. Unfortunately when importing in the react-starter-app I am getting the following error 

```
../react-formio/lib/utils.js
Module not found: Can't resolve 'formiojs' in '~/projects/react-formio/lib'
```

The workflow I am using is as follows:
- `npm i` in formio.js
- `npm link` in formio.js
- `npm i` in react-formio
- `npm link formiojs` in react-formio
- `npm i` in react-starter-app
- `npm link react-formio` in react-starter-app

Anything that I am doing wrong or is there a different workflow to test the changes ?

**Comment by travist** [comment]
I believe the issue is that you are linking from the wrong directory in formiojs. For now (we will change this in 5.x) when you link formiojs, you need to do so from the "lib" folder and not the root. When we publish to npm for formiojs, we do so from that directory. 

Hope this helps.
