### ISSUE TITLE
[BUG] React-formio fails to load in production environment

### ISSUE THREAD

**Issue by bdkruse** [formio/react-formio#283]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: formiojs@4.7.8
- react-formio version: react-formio@4.2.4
- Frontend framework: react@16.12.0
- Backend framework: Rails@6.0.0
- Asset compilation: Webpacker
- Browser: Chrome
- Browser version: Latest

## Expected behavior
- Deployed app should work like development environment.

## Observed behavior
- react-formio works as expected in development environment but does not work in production environment. The only error found was in the browser console. screenshot attached.
![Screen Shot 2020-01-13 at 3 22 26 PM](https://user-images.githubusercontent.com/18729253/72293177-94b18b80-3618-11ea-86f8-dba716ae3bbf.png)

## Example component
```
class FormEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      schema: null
    };
    this.setSchema = this.setSchema.bind(this);
  }

  componentDidMount() {
    if (this.props.schema) {
      this.setState({ schema: JSON.parse(this.props.schema) });
    }
  }

  setSchema = (schema) => {
    this.setState({ schema });
  }

  render() {
    const { schema } = this.state;
    const { controllerAction, inputName } = this.props;
    if (controllerAction === "new") {
      return (
        <Col>
          <hr />
          <FormBuilder form={{ display: "form" }} onChange={(newSchema) => this.setState({ schema: newSchema })} />
          <input type="hidden" name={inputName} value={JSON.stringify(schema)} />
        </Col>
      );
    }
    return (

      <div>
        { schema
        && (
          <Col>
            <hr />
            <FormBuilder
              form={schema}
              onChange={(newSchema) => this.setSchema(newSchema)}
            />
            <input type="hidden" name={inputName} value={JSON.stringify(schema)} />
          </Col>
        )}
      </div>

    );
  }
}
```

**Comment by randallknutson** [comment]
We don't have a component named FormEditor in our library. We also have lots of apps compiling just fine with webpack using react-formio. Can you double check that it isn't something in your code?

**Comment by bdkruse** [comment]
FormEditor is a component that uses the FormBuilder component from react-formio

**Comment by randallknutson** [comment]
If I understand correctly, that means that FormEditor is not being registered properly with react so that where you are using it doesn't know where it exists. This might work in Dev because the component ends up as a global or in scope but in your compiled version it is locally scoped and doesn't exist correctly. Make sure you do an import correctly before you use the component in its parent component.
