### ISSUE TITLE
this.dataValue always null

### ISSUE THREAD

**Issue by PhilipeGatis** [formio/react-formio#286]
My customComponent always get null from dataValue.
I don`t know what i doing wrong.

to test i put in attachReact function one console.log...

![image](https://user-images.githubusercontent.com/4982462/74367827-475c4180-4db1-11ea-97e6-3aa38d534d07.png)

**Comment by randallknutson** [comment]
This probably means that it is never saving the data to the submission, thus this.dataValue is always null. If you implement setValue and getValue correctly it will do that in updateValue of Component.js.

**Comment by PhilipeGatis** [comment]
@randallknutson i use the reactComponent class to create the custom component. This class has default implementation of set and getValue functions. But the problem is the initial valeu seted by submisions prop on Form component.
I follow this example to implement my componenet: https://github.com/formio/react-app-starterkit/blob/master/src/components/ReactExample/ReactExample.jsx

**Comment by PhilipeGatis** [comment]
@randallknutson I discover the problem. My component it's a function component and functions components don't has an instance.

The custom components extends the reactComponent class and this class need a react instance class to set the value to state. 
https://github.com/formio/react-formio/blob/master/src/components/ReactComponent.jsx
https://github.com/formio/react-formio/blob/master/src/components/ReactComponent.jsx#L60
https://github.com/formio/react-formio/blob/master/src/components/ReactComponent.jsx#L103

**Comment by travist** [comment]
Glad you got it figured out. Is there any documentation we could add on our end to ensure the next person who runs into this can have a quick solution?

**Comment by PhilipeGatis** [comment]
@travist No. Has comments at react Component class informing about this.
But i think can make an improvement to accept component functions.

Thanks.

**Comment by randallknutson** [comment]
Glad you figured it out!

**Comment by darshanksexathought** [comment]
I am still facing this issue this.reactInstance is null always so it is not able to set the value

**Comment by simonv3** [comment]
It would be cool to get something working for function components, since that's the way React is going.

**Comment by Alexa-Green** [comment]
@PhilipeGatis What did you do to fix this? Have a class component rendering a function component, setValue is working but not the initial value. Tried calling onChange on componentDidMount but it is overwriting with createInitialFields() even though submission data has been saved

```
const MyCustomComp = class extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: props.value || createInitialFields(),
    };
  }

  // Set the initial value to make it available in custom validation and calculation `data` objects
  componentDidMount() {
    this.props.onChange(this.state.value, null);
  }

  setValue = (key, sub, value) => {
    this.setState(
      (prevState) => ({
        value: {
          ...prevState.value,
          [key]: { ...prevState.value[key], [sub]: value },
        },
      }),
      () => this.props.onChange(this.state.value, null)
    );
  };

  render() {
    return (
      <ThemeProvider>
        <FunctionComponent value={this.state.value} setValue={this.setValue} />
      </ThemeProvider>
    );
  }
};

export default class MyCustom extends ReactComponent {
  static get builderInfo() {
    return {
      title: 'My Custom',
      icon: 'square',
      group: 'Premium',
      documentation: '',
      weight: -10,
      schema: MyCustom.schema(),
    };
  }

  static schema() {
    return ReactComponent.schema({
      type: 'mCustomComp',
      label: 'My Custom',
    });
  }

  static editForm = settingsForm;

  attachReact(element) {
    return ReactDOM.render(
      <MyCustomComp
        component={this.component}
        value={this.dataValue}
        onChange={this.updateValue}
      />,
      element
    );
  }

  detachReact(element) {
    if (element) {
      ReactDOM.unmountComponentAtNode(element);
    }
  }
}
```
