### ISSUE TITLE
[BUG] https://cdn.form.io/ace/1.4.8/theme-snow.js not found

### ISSUE THREAD

**Issue by AgileFlexAgency** [formio/react-formio#291]
## Environment
Please provide as many details as you can:

https://cdn.form.io/ace/1.4.8/theme-snow.js not found.

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by travist** [comment]
We have seen this and is put as a priority.  Not sure yet when you can see an update since we are pretty overloaded at the moment, but it may be next week before we can get to the fix.

**Comment by jhen1422** [comment]
@AgileFlexAgency This issue should be resolved in formio.js version 4.9.16

**Comment by AgileFlexAgency** [comment]
@jhen1422 We'll update the npm packages and test the code with the new version.

Thank you for your great support @jhen1422 @travist @randallknutson
