### ISSUE TITLE
[BUG] Multiple errors on binding the form to the Form Builder

### ISSUE THREAD

**Issue by AgileFlexAgency** [formio/react-formio#295]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io - "formiojs": "^4.9.5", "react-formio": "^4.3.0",
  - [ ] Local deployment
    - Version: 
- Formio.js version: "formiojs": "^4.9.5"
- Frontend framework: "react": "^16.12.0",
- Browser: Chrome 
- Browser version: 80.0.3987.149

## Steps to Reproduce
1. From a drop down select another schema (its content is returned by an API) and then bind to the Form Builder 
2. Sometimes the process is successful but sometimes is not  
3. It is expected that the bind should be without errors

## Expected behavior
    Clean bind of the form in the Form Builder
## Observed behavior
    Errors thrown on the console
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

**Form.io console logs can be found in this text file**: 
[formio-errors.txt](https://github.com/formio/react-formio/files/4407576/formio-errors.txt)

For code or form JSON, please enclose in a code block:

 ```html 
<FormBuilder
     ref={formioRef}                    
     options={formioOptions}
     form={formioSchema}
    onChange={(schema) => { }}
/>
```

```js
componentDidUpdate(prevProps, prevState) {
        // props are updated on selecting a schema name from a drop down
        // based on the schema id its content is returned from an API
        const { schema } = this.props;

        if (this.props !== prevProps) {
            if (schema && schema.schema) {
                this.setState({
                    schemaTemplate: schema.schema,
                });
            }
        }
    }
}

render() {
    const { schemaTemplate } = this.state;
    const formioSchema = schemaTemplate ?  JSON.parse(schemaTemplate) : { display: 'form' };
}
```

**Comment by randallknutson** [comment]
This sounds like a race condition where the detach or destroy event is occurring after the old form is unmounted. Is this something you could put some breakpoints in and see if you can isolate what is going wrong?

**Comment by AgileFlexAgency** [comment]
Hello @randallknutson Thank you for quick answer. 
There is a **formio-errors.txt** attached in the message above. Please let me know if it is helpful or if you need additional info.

Kind regards, Daniel Luca

**Comment by AgileFlexAgency** [comment]
@randallknutson One of the errors is thrown when switching from a template that contains a **Date Picker (flatpickr)** to one that doesn't.

Please analyse the attached log in txt format.
[date-input-flatpicker-debug.txt](https://github.com/formio/react-formio/files/4413318/date-input-flatpicker-debug.txt)

**Comment by randallknutson** [comment]
Thanks for the debug logs. We aren't currently seeing this with our other customers at the moment which puts this at a lower priority for us to look into. Would you be interested into either debugging what is wrong and contributing a fix or purchasing a support contract to look into the issue for you?
