### ISSUE TITLE
[BUG] Hi Form.io team, I have a query regarding dynamic select filtering in formio.......I have checked https://help.form.io/tutorials/walkthroughs/dynamic-select-filtering/ ..........this link in which i see , the above example itself is not working , i am giving my try to use formio for my self knowledge and i have faced an issue as i am not able to manipulate the second dropdown value based on the first drop-down selection (DYNAMIC SELECT FILTERING without any URL it should be locally) , can you please look into this , as i find this feature very common in my project i am making

### ISSUE THREAD

**Issue by rakeshkumar001** [formio/react-formio#298]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version:  
- Formio.js version: i have used npm react formio
- Frontend framework: React
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by wag110894** [comment]
This is an old example.  Here is an updated example:https://formio.github.io/formio.js/app/examples/external.html
