### ISSUE TITLE
[BUG] Change page name in wizard type. 

### ISSUE THREAD

**Issue by ductm-devblock** [formio/react-formio#304]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: react-formio 4.3.0 (or >= 4.2.3)
- Frontend framework: ReactJS 16.12.0
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. Create wizard form
2. Change page label
3. Click on different tabs

## Expected behavior
Page label is changed (In panel component and page tab)

## Observed behavior
Page label not changed (In panel component and page tab)

## Example
![image](https://user-images.githubusercontent.com/61770453/81266242-a22ecd80-906e-11ea-822d-19781a5fdd97.png)

A live example:
https://codesandbox.io/s/blazing-feather-n0sq5

**Comment by wag110894** [comment]
Hello @ductm-devblock,
Thank you for reaching out! We are able to replicate this issue on our side. We have created a ticket and have added this item to our backlog. We welcome a PR or have a process to expedite if you are interested. 

In the meantime, you will need to save the form in order for the navigation bar to update.

We will let you know once this has been resolved.

**Comment by wag110894** [comment]
@ductm-devblock,

Thank you for your patience while we worked on resolving this issue. This has been resolved in 4.10.0-rc.3. 


Thanks for using Form.io
