### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Bdestasio33** [formio/react-formio#309]
This is just a bug with the documentation. On the form builder props, one of the properties reads `updateComponent` for when the component updates when it should read `onUpdateComponent` instead. This had me racking my brain for a while.

**Comment by randallknutson** [comment]
Thanks for pointing this out. Fixed here: https://github.com/formio/react-formio/commit/b0ff81690e098afc66b5167936a7e847dd71ad11#diff-04c6e90faac2675aa89e2176d2eec7d8
