### ISSUE TITLE
[BUG]  Errors and Inconsistent Behavior in Tabs Component

### ISSUE THREAD

**Issue by nathancoates** [formio/react-formio#312]
## Environment
Please provide as many details as you can:

- Hosting type
  - Local Deployment
    
- Version: 
- Formio.js version: 4.9.26
- Frontend framework: react-formio 4.3.0
- Browser: Chrome
- Browser version: 83.0.4103.61 

## Steps to Reproduce
1. Drag Tabs component into Builder
2. Add tabs
3. Save

## Expected behavior
Tab schema updates correctly and no errors in console

## Observed behavior
When I add two tabs and save, in the console I see: 
`Tabs.js:95 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at Tabs.js:95
    at Array.map (<anonymous>)
    at TabsComponent.get (Tabs.js:94)
    at WebformBuilder.js:1231`

I am also logging out the schema, and the key for each of the tabs is "tab2" even if they have been named Tab 1 and Tab 2. If I add a third Tab named Tab 3, the keys are corrected in the next log statement, but I get the TypeError again.

I also have a form renderer component in my application so I can test the changes I make in the builder. When I add the first two tabs, only the first one is rendered in the form. Then when I add the third, only the first two are rendered.

**Comment by wag110894** [comment]
@nathancoates Thank you for reaching out!

We are not able to replicate the Type Error on the latest version of formio.js (4.10.0-rc12). 

We are able to replicate the key changing to when clicking on the add Another button. We have created a ticket  (FJS-996) and have added this to our backlog. We welcome a Pull Request and have a process to expedite. If you are interested in expediting this bug, then please contact support@form.io.

We are not seeing any rendering issues on our side on the latest version of formio.js. Can you recheck when you upgrade and see if you are still able to replicate?

**Comment by wag110894** [comment]
@nathancoates  FJS-996 has been resolved on our latest build of 4.10.0.

Have a great day!

**Comment by nathancoates** [comment]
Thank you!



*Nathan Coates*
*Software Engineer*
c: 804 833.5819 <+18048335819>

<http://ipponusa.com/>
