### ISSUE TITLE
[BUG] Does not submit the form via json

### ISSUE THREAD

**Issue by yosdanybm** [formio/react-formio#316]
I have the following problem, this is my form via json:

`<Form
             form={this.state.formJson}
             url="'https://formio.server.com'"
             options={this.state.options}
   />`

It happens, when running the submit shows the submit completed alert but does not send anything this by the way **json**, however by the way **src** if you send it, it is something so basic but I do not find the solution, I expect your help.

### Environment

- react-formio: "^4.3.0",

**Comment by randallknutson** [comment]
When using the Form component, there are two ways to pass the form definition. The first is using src which points to the form url. The second is to use the form attribute along with url which will cause the form not to submit anywhere. You need to listen to the onSubmit event and respond when the user presses the submit button. 

https://github.com/formio/react-app-starterkit/blob/master/src/views/Form/Item/Submission/Item/Edit.js#L32
