### ISSUE TITLE
Data source type : URL for checkbox or radio

### ISSUE THREAD

**Issue by SergeyMelnyk** [formio/react-formio#332]
hi every one, can you help me and tell , does it posible make Data source type : URL for checkbox or radio like this has select component

**Comment by randallknutson** [comment]
This is a feature we would love to add and have had it on our backlog. Right now the only way to add options from a URL is in the Select component. We would like to mimic the same functionality for the Radio and checkboxes components. This can be done with the current system but it is not easy. You need to load the options into the submission using the DataSource (premium) component and then use Field Logic to "Merge Component Schema" and modify the data options of the Radio/Selectboxes.
