### ISSUE TITLE
React-Formio custom component

### ISSUE THREAD

**Issue by SergeyMelnyk** [formio/react-formio#348]
Hello everyon, can you help me with custom component, i created few custom component but the render outside general tree componen, outside Router Reduxa and outher Context

![image](https://user-images.githubusercontent.com/39995312/99229939-5916bd80-27f7-11eb-93b7-99a1ec4e4c5f.png)

**Comment by wag110894** [comment]
@SergeyMelnyk, 

We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.  Please let me know if you are interested and I can provide you our Support Package Options.

**Comment by darshanksexathought** [comment]
@wag110894 can you please send me the support package details?

**Comment by wag110894** [comment]
Hello @darshanksexathought, 

Absolutely. Can you provide your email address? That way we can send it over.

**Comment by darshanksexathought** [comment]
@wag110894  here isy mail id darshan.ks@exathought.com

**Comment by wag110894** [comment]
Email has been sent.

**Comment by SergeyMelnyk** [comment]
@wag110894 can you please send me the support package details too ?
my email melnykserhiy1@gmail.com

**Comment by SergeyMelnyk** [comment]
@darshanksexathought did you have same problem?

**Comment by darshanksexathought** [comment]
I did not understand your problem

**Comment by SergeyMelnyk** [comment]
@darshanksexathought @wag110894 i found same trouble in this code https://codesandbox.io/s/custom-formio-component-in-react-81qb6?from-embed, try add toogle on form and look at react dev tools, 
component toogle, outside main wrapper App , and hi 2 https://i.imgur.com/DwU7iku.png
