### ISSUE TITLE
How to customize paste/edit json options.

### ISSUE THREAD

**Issue by Anandks1993** [formio/react-formio#351]
Thank you for this wonderful package.

This is not an ISSUE, I just have some questions for customization.

- Hosting type
  - [x] JSON Schema
- Formio.js version: 4.9.16
- Frontend framework: React v15.3.0

<img width="102" alt="Edit-Tooltip" src="https://user-images.githubusercontent.com/26414695/100055681-38c7ae00-2e4a-11eb-9d99-6bf29c512a44.png">

1) Is there a way to customize the options when we hover fields?

<img width="80" alt="help-icon" src="https://user-images.githubusercontent.com/26414695/100055854-96f49100-2e4a-11eb-9b7d-b241bbe7f37b.PNG">

2) Also is there a way to hide the help icon?

--Is this possible to hide these without using CSS?

3) Can we move fields from one group to another (e.g, from Advanced to Basic)

**Comment by travist** [comment]
All of these customizations would need to be made to the "core" renderer @ https://github.com/formio/formio.js and can be done. For example, the templates can be modified by following the tutorial @ https://github.com/formio/formio.js/wiki/Templates-API  This should answer most of your questions.

As for moving fields from one group to another, this can also be done by creating a custom form builder configuration. See https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by Anandks1993** [comment]
@travist Thank you, I will take a look into those.

**Comment by Anandks1993** [comment]
@travist Is it possible to have SUBMIT button always there on the formbuilder?

**Comment by travist** [comment]
Are you referring to the Form submit button?  It should be there.  What version of the core renderer are you using?

**Comment by Anandks1993** [comment]
@travist Sorry that I didn't ask my question well, yes the submit button is there always, I just don't want users to remove that, on hover users will see an option to remove each field but for Submit button I don't want to show the remove option. 

I just thought about one solution for my case, I thought of not showing the submit button in the formbuilder and only show that in formrenderer.

I just want to know if there is an option to hide remove option only for submit button. If not I think the solution I referred is enough.

**Comment by travist** [comment]
I bet it is possible to hide the overlay with CSS. Have you tried to do that in your own application?

**Comment by Anandks1993** [comment]
@travist  Yeah I tried to hide the overlay only for `SUBMIT` button but all the overlay seems to have same class names. The options (edit, move, copy etc.,) is a sibling which comes before the `SUBMIT` element, so I could not use the help of SUBMIT button's class name to target the overlay. 

So I am thinking to not show the SUBMIT button in the builder and remove `BUTTON` component, then I can insert the submit button in the form renderer for submitting purpose.
