### ISSUE TITLE
[BUG] Error in building the app (core-js - cannot resolve module)

### ISSUE THREAD

**Issue by Anandks1993** [formio/react-formio#357]
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 4.3.0
- Formio.js version: 4.9.16
- Frontend framework: react (v15.3.0)
- Browser: any
- Browser version: any

Everything worked fine in local development, app was up and running without any error, But when I tried to build the app to deploy I am getting the following issue. It seems to be due to CORE-JS module.

![image](https://user-images.githubusercontent.com/26414695/101602139-a3204700-3a23-11eb-9fed-5dff2a0a82c5.png)

And I am getting some warning regarding dragula js

![image](https://user-images.githubusercontent.com/26414695/101613759-26489980-3a32-11eb-982d-667b0df9baf1.png)

**Comment by travist** [comment]
This is probably a difference is "core-js" versions. Type the following and let me know what it says.

```
npm ls core-js
```

**Comment by Anandks1993** [comment]
@travist This is what I got, when I tried that command you mentioned.
![error](https://user-images.githubusercontent.com/26414695/101773784-413f0a80-3b13-11eb-992e-8295f7b29944.png)

**Comment by travist** [comment]
Some of them are using 1.27 , others are using 2.4.1, and others are using 3.1.4.  This is a version mismatch issue and can probably be resolved by upgrading all libraries to the latest versions.

**Comment by Anandks1993** [comment]
@travist Updating the packages is the problem for us as we are using react older version(v15.3.0) so I added `core-js` latest version as dependency to the project and the build is working fine now. Is this approach ok to resolve this?

**Comment by travist** [comment]
Yes, you should be good.

**Comment by Anandks1993** [comment]
@travist Thank you very much. Do you have any idea how to remove the warning coming from dragula js?
