### ISSUE TITLE
First row data not getting populated in data grid with merge component schema

### ISSUE THREAD

**Issue by pratikpbhagat** [formio/react-formio#374]
I 'am having a select drop down Approach (with 2 values - Product Based and Process Based). I have added the below Advanced Logic on selection of the one of the values for the data grid with columns(using Text Area) like riskEvent, baselLevelI, baselLevelIi, baselRiskCategory, control and controlCategory

Type - Simple
When the Form Component - Approach
Has the Value - Product Based

Action Type - Merge Component Schema

Schema Definition

```
var values = [
                {
                    "riskEvent": "a",
                    "baselLevelI": "aa",
                    "baselLevelIi": "aaa",
                    "baselRiskCategory": "aaaa",
                    "control": "aaaaa",
                    "controlCategory": "aaaaaa"
                },{
                    "riskEvent": "e",
                    "baselLevelI": "ee",
                    "baselLevelIi": "eee",
                    "baselRiskCategory": "eeee",
                    "control": "eeeee",
                    "controlCategory": "eeeeee"
                },
				{
                    "riskEvent": "f",
                    "baselLevelI": "ff",
                    "baselLevelIi": "fff",
                    "baselRiskCategory": "ffff",
                    "control": "fffff",
                    "controlCategory": "ffffff"
                }
            ]	;

console.log(values);

schema = {
	defaultValue: 		values
}
```

The values in the first row are not displayed and the text area remains empty, whereas the values in the second row onwards are correctly displayed in the data grid

**Comment by travist** [comment]
What version of the imported "formiojs" library are you using? I want to think that this issue was resolved with the latest versions of our renderer (formiojs) which is imported into the react-formio library.

**Comment by pratikpbhagat** [comment]
> What version of the imported "formiojs" library are you using? I want to think that this issue was resolved with the latest versions of our renderer (formiojs) which is imported into the react-formio library.

Below are the entries in my package.json

`"formiojs": "^4.0.0-rc.21"`,
`"react-formio": "^4.2.6",`

**Comment by AlexeyDavyd** [comment]
@pratikpbhagat
We have 5.0.0-rc.2 release of react-formio that supports latest formiojs version and peer dependencies.
You could try to update your react-formio and formiojs versions to latest.

**Comment by pratikpbhagat** [comment]
Thanks, resolved by using the updated version
