### ISSUE TITLE
npm install react-formio

### ISSUE THREAD

**Issue by aminmc** [formio/react-formio#380]
Hello

I'm trying to install react-formio using nom and I'm on react 17.0.1. When I try to execute the command I get the following:

```
npm install react-formio formiojs --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: XXXX@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-formio@4.3.0
npm ERR! node_modules/react-formio
npm ERR!   react-formio@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Anyone else experiencing this issue?

**Comment by wag110894** [comment]
Hello @aminmc,

Thanks for reaching out! We are able to replicate this issue and have added it to our backlog. We welcome a PR and we also have a process to expedite the issue.

For reference, the ticket is FIO-2090.

**Comment by aminmc** [comment]
@wag110894 Is there any updates on this?

**Comment by wag110894** [comment]
Hello @aminmc,
I just got the below information from one of our developers:

The latest released version of react-formio specifies react as a peer dependency with version ^15.0 || ^16.0, that’s why npm@7.x throws an error (does not happen with npm 6)
You still can install it , but you need to install it using the following command
npm i --save react-formio --legacy-peer-deps
Also, react-formio v5 is coming soon where 17.x version of react is specified in peer dependencies
