### ISSUE TITLE
Error installing react-formio

### ISSUE THREAD

**Issue by psrinivasamurthy** [formio/react-formio#4]
I am giving this command npm install react-formio but I get this warning and the form is not able to render

~/react-formio/dist/build/Formio.js
Critical dependencies:
1:479-486 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-formio/dist/build/Formio.js 1:479-486

**Comment by randallknutson** [comment]
We now have an example of how to embed the react-formio library with webpack and compiling from source. See https://github.com/formio/react-example.
