### ISSUE TITLE
Running the TODO app 

### ISSUE THREAD

**Issue by ccristian** [formio/react-formio#75]
This is not a big issue just worth mentioning as is easy to fix
The Task app 
https://portal.form.io/#/project/57fd3190581e59007c155554/local
description to run app locally is confusing (at least it was for me) 
No mention of how to install gulp as for example is mentioned 
https://github.com/formio/formio-app-basic
Cheers

**Comment by randallknutson** [comment]
Can you post your request either to support@form.io or in the the https://github.com/formio/formio-app-basic repository? Your question deals with that code and not the React renderer which is where you posted it.
