### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by pfrohner** [formio/react-formio#76]
Build fails, these dependencies are seem to be missing:

"react-widgets" and "formiojs"

**Comment by randallknutson** [comment]
Those are in the package.json. Can you run npm install again and see if that fixes it for you?

**Comment by pfrohner** [comment]
thanks for the quick reply!

it's missing from the last release's package.json

**Comment by randallknutson** [comment]
Which version are you using? It is included in v0.10.5

https://github.com/formio/react-formio/blob/v0.10.5/package.json

**Comment by randallknutson** [comment]
Ah, you are referring to the react-example app. You can use that as a simple example of rendering React. We are in the middle of creating a new starterkit that will have even more information on building apps in React with Form.io.

**Comment by pfrohner** [comment]
oh sorry, yeah, I was trying to make the example work, thats where I had the missing dependencies but the create ticket took me to the main formio project...
