### ISSUE TITLE
Tab support ??

### ISSUE THREAD

**Issue by Diaskhan** [formio/react-formio#80]
Goo days, there wiil be a support of tabs ??
The modules are very functional, but has no support of Tabs, it hard to use form builder with no tabs in every version react,ng2, and angularjs

**Comment by randallknutson** [comment]
Tabs are now supported in all versions of formio renderers (react, ng2, angularjs, vue, aurelia). We don't have a UI to build them yet on portal.form.io but custom form builders have them already. We will be updating portal with the tabs builder as soon as possible.
