### ISSUE TITLE
Select Components - Enable credentials on URL Option

### ISSUE THREAD

**Issue by mrbarletta** [formio/react-formio#81]
Awesome jobs folks, I think it has a lot  of potential as an enterprise tool.

The select component values can be retrieved from a URL, but credentials are not sent during the request and if the values are behind some authentication it fails.

Is it possible to enable a "Credentials" checkmark at the form/component level to enable the 'credentials' flag on the request?

Further in the future maybe an Authentication option to specify more properties.

Thanks!

**Comment by randallknutson** [comment]
It is possible to pass credentials in the url querystring but currently not in the header. What type of Credentials do you need?

**Comment by mrbarletta** [comment]
@randallknutson Thanks for keeping track of this issue.

In that specific scenario I needed to send cookies with the fetch, the browser already has authentication details in the cookies so I wanted to send them. 
But also enabling JWT kind of Authorization headers will be great.   

What do you think?

**Comment by rankin** [comment]
I'm having the same issue. The form works fine in form.io but when I load it with react-formio the headers are stripped. I'm working on a fix and will make a PR.

**Comment by rankin** [comment]
Created a PR for this: #103

**Comment by aminmc** [comment]
Any updates on this? It's been open since 2017.  We have the same requirement and I'm surprised this hasn't been incorporated.

**Comment by randallknutson** [comment]
This should be done now. The PR was pulled into the 1.x branch and 2.x and later support custom headers and passing formio.js auth token.
