### ISSUE TITLE
How to run whole project instead of single form.

### ISSUE THREAD

**Issue by SaurabhKshirsagar** [formio/react-formio#84]
`ReactDOM.render(<Formio src="https://someFormId.form.io/user/login"></Formio>
  , document.getElementById('app')
);`

This only renders a single form.
Is there a way to redirect/navigate from one form to another in a react app?

**Comment by randallknutson** [comment]
Hi Saurabh, The main renderer just does a form. It is designed to live within any react app that is built to facilitate development. There is a repo we have to get you started faster with an app at https://github.com/formio/react-app-starterkit
