### ISSUE TITLE
current react-formio version is now broken because of the latest react-router release

### ISSUE THREAD

**Issue by joxerTMD** [formio/react-formio#88]
Hi there! The latest react-router release (v4.0.0-beta.2) is not exporting propTypes in [index.js](https://github.com/ReactTraining/react-router/blob/cfc053ec7bea4f0dd718e252265bc36e89e229fc/packages/react-router/modules/index.js) anymore. So now [this line of code](https://github.com/formio/react-formio/blob/ae01102da9bd69da5c6b06bb158f16a52631ffd2/lib/providers/FormioAuth/components/FormioLogout.js#L92) is broken, and whole react-formio library cannot be required correctly. So i guess you should fix your package.json file or migrate to the latest react router version.

**Comment by randallknutson** [comment]
Yup. Looks like they aren't exporting that any more. I'll update it to fix this.

**Comment by randallknutson** [comment]
Fixed in https://github.com/formio/react-formio/commit/e5aafc1571a3315a764aa9d0008844ed37d1d55d

Release coming shortly.

**Comment by randallknutson** [comment]
Fixed in v1.0.0-alpha14
