### ISSUE TITLE
Select Component - Cannot update during an existing state transition

### ISSUE THREAD

**Issue by mrbarletta** [formio/react-formio#90]
A Select component using CUSTOM data + RefreshOn Anychange (data) fails with error
```
setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
```

Reproduction : Using an existing form
1) Create Select component 
2) Set Data source of Select component  as Custom.
3) Fill data source with `values=[{ label: '1', name:'one'}]`
4)  Refresh React page that points to the said form and type anything on the form.

**Comment by randallknutson** [comment]
Thanks for the report on this. I've seen it but wasn't sure how to track it down. Will be fixed in the next release.
