### ISSUE TITLE
onFormLoad event does not work

### ISSUE THREAD

**Issue by Aiso786** [formio/react-formio#94]
Hello,

The "onFormLoad" event is not firing. Here is how i use the "Formio" react component:

`<Formio
       submission={this.state.entityDetailViewModel.get('entityObject').toJSON()}
       form={JSON.parse(this.state.entityDetailViewModel.get('form'))}
       onFormSubmit={this.onFormSubmit} />`

**Comment by randallknutson** [comment]
onFormLoad will only fire if you load the form from a url using the src attribute. For example:

<formio src="http://myproject.form.io/myform" onFormLoad="" />

If you pass the form directly there is nothing that is loaded and you can do whatever you want to the form before you pass it to the formio directive.

**Comment by haraldkrischner** [comment]
I've got the same problem and looking into the code I am missing the callback functionality for onFormLoad… Am I overseeing something?
