### ISSUE TITLE
Changes in #92 took no effect

### ISSUE THREAD

**Issue by joxerTMD** [formio/react-formio#96]
Hello again! Thx for replying to #93 and merging #92.
Unfortunately these changes took no effect because PR was merged after new lodash imports were created in code:(
i've prepared new PR #95 to fix this again.
I've also tried to add some linting rules like http://eslint.org/docs/rules/no-restricted-imports, to automatically prevent creating such imports in the future. But it looks like that eslint currently in broken state:( And it is not a part of the project build

**Comment by randallknutson** [comment]
merged
