### ISSUE TITLE
Address component don't call google maps api

### ISSUE THREAD

**Issue by juanmagalhaes** [formio/react-formio#98]
Hi guys!

I am doing some tests with `formio` libraries. So far I was able to encapsulate the `ngFormBuilder` inside a react component for a react application and I am using `react-formio` to render the forms from the json schemas.

I noticed that the `address` component is not making calls to the google maps api. It is working on `ngFormio` though... I Download both of the examples and ran then locally.   

- https://github.com/formio/examples.form.io (calls maps api)
- https://github.com/formio/react-example (don't call maps api)

I also noticed that the `doSearch` method inside the `address` component is responsible for the api call but it is not being called anywhere as it can be seen here:

![image](https://user-images.githubusercontent.com/13842678/26898382-1639a5d4-4ba2-11e7-8056-817ab10f8ad5.png)

Will this feature be implemented anytime soon? Would it be ok to submit a pull request?

Thanks!

**Comment by randallknutson** [comment]
The new version of the renderer should be working. You may need to set the google api key to make it fully work though. Also, in the 2.1 and 3.x versions of react-formio we now have a version of the form builder so you should no longer need to use the ngFormBuilder wrapper.
