### ISSUE TITLE
Survey component has a bug

### ISSUE THREAD

**Issue by juanmagalhaes** [formio/react-formio#99]
Survey component is allowing you to mark many options on the same row.

![image](https://user-images.githubusercontent.com/13842678/26941653-9a65787a-4c55-11e7-8cf4-512df4592657.png)

It is currently trying to access a property from a variable that should be an object though it is actually a string...

This was tested on the https://github.com/formio/react-example project.

Is this bug known? Is this fix on the roadmap? I might be of some help, maybe even submit a Pull Request.

**Comment by randallknutson** [comment]
This should be fixed in the latest versions of the renderer. Please let us know if not.
